kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "tie-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/nikio-io/task-it-easy.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
