apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: task-it-easy
  name: task-it-easy
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/nikio-io/task-it-easy.git'
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      env:
        - name: APP_NAME
          value: tie
        - name: DOCKER_REGISTRY
          value: 'docker-registry.default.svc:5000'
        - name: DEV_PROJECT
          value: tie-dev
        - name: STAGE_PROJECT
          value: tie-stage
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5